FROM fedora:28 as build

RUN set -x && \
    INSTALL_PKGS="git java-1.8.0-openjdk maven rsync tzdata libaio" \
    && yum clean all && rm -rf /var/cache/yum/* \
    && yum install -y $INSTALL_PKGS  \
    && yum clean all \
    && rm -rf /var/cache/yum
